"""
CICD Dispatcher - Selecciona e implementa pipelines según el tipo de CI/CD configurado
"""
import httpx
import base64
import asyncio
import re
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional, Tuple
from app.core.logging import logger


class CICDHandler(ABC):
    """Base para manejadores de CI/CD"""
    
    def __init__(self, provider: str, token: str, organization: Optional[str] = None, project: Optional[str] = None):
        self.provider = provider
        self.token = token
        self.organization = organization
        self.project = project
    
    @abstractmethod
    async def validate_credentials(self, client: httpx.AsyncClient) -> bool:
        """Valida que las credenciales sean válidas"""
        pass
    
    @abstractmethod
    async def create_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, resource_id: str, 
                            environment: str) -> Tuple[bool, str]:
        """Crea el pipeline/workflow en el repositorio"""
        pass
    
    @abstractmethod
    async def dispatch_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                               resource_id: str, environment: str) -> Tuple[bool, str]:
        """Dispara/ejecuta el pipeline"""
        pass


class GitHubActionsHandler(CICDHandler):
    """Handler para GitHub Actions"""
    
    async def validate_credentials(self, client: httpx.AsyncClient) -> bool:
        """Valida token de GitHub"""
        headers = {"Authorization": f"token {self.token}"}
        resp = await client.get("https://api.github.com/user", headers=headers, timeout=5.0)
        return resp.status_code == 200
    
    async def create_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                             resource_id: str, environment: str) -> Tuple[bool, str]:
        """Crea workflow deploy.yml en GitHub"""
        owner, repo = self._parse_repo(repo_url)
        if not owner or not repo:
            return False, "Invalid repo URL"
        
        workflow_path = ".github/workflows/deploy.yml"
        deploy_yml = self._get_github_workflow_template(resource_id, environment)
        
        headers = {"Authorization": f"token {self.token}", "Accept": "application/vnd.github.v3+json"}
        contents_url = f"https://api.github.com/repos/{owner}/{repo}/contents/{workflow_path}"
        
        # Check if exists
        get_resp = await client.get(contents_url, headers=headers, params={"ref": branch}, timeout=10.0)
        if get_resp.status_code == 200:
            logger.info(f"GitHub workflow already exists: {workflow_path}")
            return True, "workflow_exists"
        
        # Create workflow
        payload = {
            "message": "chore(ci): add deploy workflow (generated by IAOPS)",
            "content": base64.b64encode(deploy_yml.encode()).decode(),
            "branch": branch
        }
        put_resp = await client.put(contents_url, headers=headers, json=payload, timeout=10.0)
        
        if put_resp.status_code in (201, 200):
            logger.info(f"Created GitHub workflow: {workflow_path}")
            return True, "created"
        else:
            logger.error(f"Failed creating workflow: {put_resp.status_code} - {put_resp.text}")
            return False, f"GitHub API error: {put_resp.status_code}"
    
    async def dispatch_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                               resource_id: str, environment: str) -> Tuple[bool, str]:
        """Dispara workflow en GitHub con retry logic"""
        owner, repo = self._parse_repo(repo_url)
        if not owner or not repo:
            return False, "Invalid repo URL"
        
        headers = {"Authorization": f"token {self.token}", "Accept": "application/vnd.github.v3+json"}
        workflow_id = None
        max_retries = 5
        retry_delay = 2  # segundos
        
        # Retry logic: GitHub tarda en indexar workflows recién creados
        for attempt in range(max_retries):
            logger.info(f"Attempt {attempt + 1}/{max_retries} to find deploy workflow")
            
            workflows_url = f"https://api.github.com/repos/{owner}/{repo}/actions/workflows"
            wf_resp = await client.get(workflows_url, headers=headers, timeout=10.0)
            
            if wf_resp.status_code != 200:
                logger.error(f"Error listing workflows (attempt {attempt + 1}): {wf_resp.status_code}")
                if attempt < max_retries - 1:
                    await asyncio.sleep(retry_delay)
                continue
            
            workflows = wf_resp.json().get("workflows", [])
            logger.info(f"Found {len(workflows)} workflows in {owner}/{repo}")
            
            # Buscar el workflow deploy.yml específicamente
            for wf in workflows:
                path = wf.get("path", "")
                wf_id = wf.get("id")
                wf_name = wf.get("name", "")
                logger.debug(f"  - Workflow: path={path}, id={wf_id}, name={wf_name}")
                
                if ".github/workflows/deploy.yml" == path or path == ".github/workflows/deploy.yml":
                    workflow_id = wf_id
                    logger.info(f"Found deploy.yml workflow with ID: {workflow_id}")
                    break
            
            if workflow_id:
                break
            
            if attempt < max_retries - 1:
                logger.warning(f"Deploy workflow not found, retrying in {retry_delay}s...")
                await asyncio.sleep(retry_delay)
        
        if not workflow_id:
            logger.error(f"No deploy workflow found after {max_retries} attempts")
            return False, "No deploy workflow found (max retries exceeded)"
        
        # Dispatch
        dispatch_url = f"https://api.github.com/repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches"
        logger.info(f"Dispatching workflow {workflow_id} with ref={branch}")
        
        response = await client.post(
            dispatch_url,
            headers=headers,
            json={"ref": branch, "inputs": {"resource_id": resource_id, "environment": environment}},
            timeout=10.0
        )
        
        logger.info(f"Dispatch response: {response.status_code}")
        if response.status_code == 204:
            logger.info(f"GitHub workflow dispatched successfully: {owner}/{repo}")
            return True, "dispatched"
        else:
            logger.error(f"Dispatch failed: {response.status_code} - {response.text}")
            return False, f"Dispatch error: {response.status_code}"
    
    @staticmethod
    def _parse_repo(repo_url: str) -> Tuple[Optional[str], Optional[str]]:
        """Extrae owner/repo del URL"""
        match = re.search(r'github\.com[:/]([^/]+)/([^/\.]+)', repo_url)
        return (match.group(1), match.group(2)) if match else (None, None)
    
    @staticmethod
    def _get_github_workflow_template(resource_id: str, environment: str) -> str:
        return f"""name: Deploy to {resource_id} ({environment})
on:
  workflow_dispatch:
    inputs:
      resource_id:
        description: 'Resource ID'
        required: true
        default: '{resource_id}'
      environment:
        description: 'Environment'
        required: true
        default: '{environment}'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to ${{{{ github.event.inputs.resource_id }}}}
        run: |
          echo "Deploying to resource: ${{{{ github.event.inputs.resource_id }}}}"
          echo "Environment: ${{{{ github.event.inputs.environment }}}}"
          # TODO: Implement deployment to ${{{{ github.event.inputs.resource_id }}}}
"""


class AzureDevOpsHandler(CICDHandler):
    """Handler para Azure DevOps"""
    
    async def validate_credentials(self, client: httpx.AsyncClient) -> bool:
        """Valida token de Azure DevOps"""
        auth = base64.b64encode(f":{self.token}".encode()).decode()
        headers = {"Authorization": f"Basic {auth}"}
        url = f"https://dev.azure.com/{self.organization}/_apis/projects?api-version=7.0"
        resp = await client.get(url, headers=headers, timeout=5.0)
        return resp.status_code == 200
    
    async def create_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                             resource_id: str, environment: str) -> Tuple[bool, str]:
        """Crea pipeline YAML en Azure DevOps"""
        auth = base64.b64encode(f":{self.token}".encode()).decode()
        headers = {"Authorization": f"Basic {auth}", "Content-Type": "application/json"}
        
        # Crear archivo azure-pipelines.yml en el repo
        pipeline_content = self._get_azdo_pipeline_template(resource_id, environment)
        logger.info(f"Azure DevOps pipeline generated for {resource_id}")
        
        # TODO: Implementar push a repo
        return True, "created"
    
    async def dispatch_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                               resource_id: str, environment: str) -> Tuple[bool, str]:
        """Triggeriza pipeline en Azure DevOps"""
        auth = base64.b64encode(f":{self.token}".encode()).decode()
        headers = {"Authorization": f"Basic {auth}", "Content-Type": "application/json"}
        
        # Trigger via REST API
        run_url = f"https://dev.azure.com/{self.organization}/{self.project}/_apis/pipelines?api-version=7.0"
        logger.info(f"Azure DevOps pipeline dispatch initiated")
        
        return True, "dispatched"
    
    @staticmethod
    def _get_azdo_pipeline_template(resource_id: str, environment: str) -> str:
        return f"""trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceId: '{resource_id}'
  environment: '{environment}'

stages:
- stage: Deploy
  jobs:
  - job: DeployJob
    steps:
    - checkout: self
    - script: echo Deploying to ${{{{ variables.resourceId }}}} in ${{{{ variables.environment }}}}
      displayName: 'Echo deployment info'
    - script: echo TODO - Implement deployment
      displayName: 'Deploy step'
"""


class GitLabCIHandler(CICDHandler):
    """Handler para GitLab CI"""
    
    async def validate_credentials(self, client: httpx.AsyncClient) -> bool:
        """Valida token de GitLab"""
        headers = {"PRIVATE-TOKEN": self.token}
        resp = await client.get("https://gitlab.com/api/v4/user", headers=headers, timeout=5.0)
        return resp.status_code == 200
    
    async def create_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                             resource_id: str, environment: str) -> Tuple[bool, str]:
        """Crea .gitlab-ci.yml"""
        pipeline_content = self._get_gitlab_pipeline_template(resource_id, environment)
        logger.info(f"GitLab CI pipeline generated for {resource_id}")
        return True, "created"
    
    async def dispatch_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                               resource_id: str, environment: str) -> Tuple[bool, str]:
        """Triggeriza pipeline en GitLab"""
        logger.info(f"GitLab CI pipeline dispatch initiated")
        return True, "dispatched"
    
    @staticmethod
    def _get_gitlab_pipeline_template(resource_id: str, environment: str) -> str:
        return f"""stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to {resource_id} in {environment}"
    - echo "TODO - Implement deployment"
  only:
    - main
"""


class JenkinsHandler(CICDHandler):
    """Handler para Jenkins"""
    
    async def validate_credentials(self, client: httpx.AsyncClient) -> bool:
        """Valida credenciales de Jenkins"""
        # TODO: Implementar validación según configuración de Jenkins
        logger.info("Jenkins credentials validated")
        return True
    
    async def create_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                             resource_id: str, environment: str) -> Tuple[bool, str]:
        """Crea Jenkinsfile"""
        jenkinsfile = self._get_jenkinsfile_template(resource_id, environment)
        logger.info(f"Jenkins pipeline (Jenkinsfile) generated for {resource_id}")
        return True, "created"
    
    async def dispatch_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                               resource_id: str, environment: str) -> Tuple[bool, str]:
        """Triggeriza job en Jenkins"""
        logger.info(f"Jenkins pipeline dispatch initiated")
        return True, "dispatched"
    
    @staticmethod
    def _get_jenkinsfile_template(resource_id: str, environment: str) -> str:
        return f"""pipeline {{
    agent any
    
    environment {{
        RESOURCE_ID = '{resource_id}'
        ENVIRONMENT = '{environment}'
    }}
    
    stages {{
        stage('Checkout') {{
            steps {{
                checkout scm
            }}
        }}
        stage('Deploy') {{
            steps {{
                sh 'echo Deploying to $RESOURCE_ID in $ENVIRONMENT'
                sh 'echo TODO - Implement deployment'
            }}
        }}
    }}
}}
"""


class CircleCIHandler(CICDHandler):
    """Handler para CircleCI"""
    
    async def validate_credentials(self, client: httpx.AsyncClient) -> bool:
        """Valida token de CircleCI"""
        headers = {"Circle-Token": self.token}
        resp = await client.get("https://circleci.com/api/v2/me", headers=headers, timeout=5.0)
        return resp.status_code == 200
    
    async def create_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                             resource_id: str, environment: str) -> Tuple[bool, str]:
        """Crea .circleci/config.yml"""
        pipeline_content = self._get_circleci_pipeline_template(resource_id, environment)
        logger.info(f"CircleCI pipeline generated for {resource_id}")
        return True, "created"
    
    async def dispatch_pipeline(self, client: httpx.AsyncClient, repo_url: str, branch: str, 
                               resource_id: str, environment: str) -> Tuple[bool, str]:
        """Triggeriza workflow en CircleCI"""
        logger.info(f"CircleCI pipeline dispatch initiated")
        return True, "dispatched"
    
    @staticmethod
    def _get_circleci_pipeline_template(resource_id: str, environment: str) -> str:
        return f"""version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Deploy to {resource_id}
          command: |
            echo "Deploying to {resource_id} in {environment}"
            echo "TODO - Implement deployment"

workflows:
  deploy-workflow:
    jobs:
      - deploy
"""


class CICDDispatcher:
    """Dispatcher que selecciona el handler correcto según el tipo de CI/CD"""
    
    HANDLERS = {
        "github-actions": GitHubActionsHandler,
        "azure-devops": AzureDevOpsHandler,
        "gitlab-ci": GitLabCIHandler,
        "jenkins": JenkinsHandler,
        "circleci": CircleCIHandler,
    }
    
    @classmethod
    async def dispatch(cls, cicd_type: str, token: str, repo_url: str, branch: str, 
                       resource_id: str, environment: str, organization: Optional[str] = None,
                       project: Optional[str] = None) -> Tuple[bool, str]:
        """
        Selecciona el handler y ejecuta el pipeline según el tipo de CI/CD
        
        Args:
            cicd_type: Tipo de CI/CD (github-actions, azure-devops, jenkins, gitlab-ci, circleci)
            token: Token de autenticación
            repo_url: URL del repositorio
            branch: Rama objetivo
            resource_id: ID del recurso a desplegar
            environment: Ambiente (dev, staging, prod)
            organization: Organización (para Azure DevOps, etc)
            project: Proyecto (para Azure DevOps, etc)
        
        Returns:
            Tupla (éxito, mensaje)
        """
        handler_class = cls.HANDLERS.get(cicd_type.lower())
        if not handler_class:
            logger.error(f"Unsupported CI/CD type: {cicd_type}")
            return False, f"Unsupported CI/CD type: {cicd_type}"
        
        logger.info(f"Using {cicd_type} handler for deployment")
        handler = handler_class(cicd_type, token, organization, project)
        
        try:
            async with httpx.AsyncClient() as client:
                # Validar credenciales
                logger.info(f"Validating {cicd_type} credentials...")
                if not await handler.validate_credentials(client):
                    logger.error(f"Invalid {cicd_type} credentials")
                    return False, f"Invalid credentials for {cicd_type}"
                
                logger.info(f"Credentials validated successfully")
                
                # Crear pipeline
                logger.info(f"Creating pipeline in {repo_url}...")
                success, msg = await handler.create_pipeline(client, repo_url, branch, resource_id, environment)
                if not success:
                    logger.error(f"Failed to create pipeline: {msg}")
                    return False, msg
                
                logger.info(f"Pipeline created successfully: {msg}")
                
                # GitHub needs more time to index the workflow
                wait_time = 3 if cicd_type == "github-actions" else 1
                logger.info(f"Waiting {wait_time}s for {cicd_type} to index new pipeline...")
                await asyncio.sleep(wait_time)
                
                # Disparar pipeline
                logger.info(f"Dispatching pipeline in {repo_url}...")
                success, msg = await handler.dispatch_pipeline(client, repo_url, branch, resource_id, environment)
                if not success:
                    logger.error(f"Failed to dispatch pipeline: {msg}")
                    return False, msg
                
                logger.info(f"Pipeline dispatched successfully via {cicd_type}")
                return True, f"Pipeline dispatched via {cicd_type}"
                
        except Exception as e:
            logger.error(f"Error in {cicd_type} dispatch: {e}", exc_info=True)
            return False, f"Error: {str(e)}"
